import * as React from "react";

/**
 * Markdown renderer for brain vault notes — Obsidian-flavored: `[[target]]`
 * and `[[target|label]]` wikilinks become clickable, plus the usual
 * headings / lists / blockquotes / fenced code / inline bold-italic-code
 * and standard links. Deliberately dependency-free (mirrors the SDK's
 * minimal renderer) — vault notes are generated by pensieve, so the dialect is
 * known and small.
 */

export interface NoteMarkdownProps {
  source: string;
  /** Resolve a wikilink target (path-without-.md or a note title) to a
   * vault path; null renders the link inert (muted). */
  resolveLink: (target: string) => string | null;
  onOpen: (path: string) => void;
}

function WikiLink({
  target,
  label,
  resolveLink,
  onOpen,
}: {
  target: string;
  label: string;
  resolveLink: (t: string) => string | null;
  onOpen: (p: string) => void;
}) {
  const resolved = resolveLink(target);
  if (!resolved) {
    return <span className="text-muted-foreground/70 underline decoration-dotted">{label}</span>;
  }
  return (
    <button
      type="button"
      className="cursor-pointer text-primary underline decoration-primary/40 underline-offset-2 hover:decoration-primary"
      onClick={() => onOpen(resolved)}
    >
      {label}
    </button>
  );
}

function renderInline(
  text: string,
  key: string,
  props: Pick<NoteMarkdownProps, "resolveLink" | "onOpen">,
): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  let remaining = text;
  let idx = 0;

  while (remaining.length > 0) {
    const wiki = remaining.match(/^(.*?)(!?)\[\[([^\]]+)\]\](.*)$/s);
    const bold = remaining.match(/^(.*?)\*\*(.+?)\*\*(.*)$/s);
    const code = remaining.match(/^(.*?)`([^`]+)`(.*)$/s);
    const link = remaining.match(/^(.*?)\[([^\]]+)\]\(([^)]+)\)(.*)$/s);

    const candidates: Array<{ at: number; type: string; m: RegExpMatchArray }> = [];
    if (wiki) candidates.push({ at: wiki[1].length, type: "wiki", m: wiki });
    if (bold) candidates.push({ at: bold[1].length, type: "bold", m: bold });
    if (code) candidates.push({ at: code[1].length, type: "code", m: code });
    if (link) candidates.push({ at: link[1].length, type: "link", m: link });
    if (candidates.length === 0) {
      parts.push(remaining);
      break;
    }
    candidates.sort((a, b) => a.at - b.at);
    const best = candidates[0];
    if (best.m[1]) parts.push(best.m[1]);
    const k = `${key}-${idx++}`;

    if (best.type === "wiki") {
      const inner = best.m[3];
      const [targetRaw, alias] = inner.split("|", 2) as [string, string?];
      const target = targetRaw.split(/[#^]/)[0].trim();
      parts.push(
        <WikiLink key={k} target={target} label={(alias ?? target).trim()} {...props} />,
      );
      remaining = best.m[4];
    } else if (best.type === "bold") {
      parts.push(<strong key={k}>{renderInline(best.m[2], k, props)}</strong>);
      remaining = best.m[3];
    } else if (best.type === "code") {
      parts.push(
        <code key={k} className="rounded bg-muted px-1 font-mono text-[0.85em]">
          {best.m[2]}
        </code>,
      );
      remaining = best.m[3];
    } else {
      parts.push(
        <a
          key={k}
          href={best.m[3]}
          target="_blank"
          rel="noreferrer"
          className="text-primary underline underline-offset-2"
        >
          {best.m[2]}
        </a>,
      );
      remaining = best.m[4];
    }
  }
  return parts;
}

export function NoteMarkdown({ source, resolveLink, onOpen }: NoteMarkdownProps) {
  const inline = { resolveLink, onOpen };
  const lines = source.replaceAll("<!-- pensieve:related:begin -->", "").replaceAll(
    "<!-- pensieve:related:end -->",
    "",
  ).split("\n");
  const nodes: React.ReactNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.startsWith("```")) {
      const buf: string[] = [];
      i += 1;
      while (i < lines.length && !lines[i].startsWith("```")) {
        buf.push(lines[i]);
        i += 1;
      }
      i += 1;
      nodes.push(
        <pre key={`code-${i}`} className="my-2 overflow-x-auto rounded-md bg-muted/60 p-3 font-mono text-xs">
          {buf.join("\n")}
        </pre>,
      );
      continue;
    }

    const heading = line.match(/^(#{1,4})\s+(.*)$/);
    if (heading) {
      const level = heading[1].length;
      const cls = ["", "mb-3 mt-1 text-xl font-semibold", "mb-2 mt-5 text-base font-semibold", "mb-1.5 mt-4 text-sm font-semibold", "mb-1 mt-3 text-sm font-medium"][level];
      const Tag = `h${level}` as "h1";
      nodes.push(
        <Tag key={`h-${i}`} className={cls}>
          {renderInline(heading[2], `h-${i}`, inline)}
        </Tag>,
      );
      i += 1;
      continue;
    }

    if (line.startsWith("> ")) {
      const buf: string[] = [];
      while (i < lines.length && lines[i].startsWith("> ")) {
        buf.push(lines[i].slice(2));
        i += 1;
      }
      nodes.push(
        <blockquote key={`q-${i}`} className="my-2 border-l-2 border-primary/40 pl-3 text-sm text-muted-foreground">
          {buf.map((b, bi) => (
            <p key={bi}>{renderInline(b, `q-${i}-${bi}`, inline)}</p>
          ))}
        </blockquote>,
      );
      continue;
    }

    if (line.match(/^[-*]\s+/)) {
      const items: string[] = [];
      while (i < lines.length && lines[i].match(/^[-*]\s+/)) {
        items.push(lines[i].replace(/^[-*]\s+/, ""));
        i += 1;
      }
      nodes.push(
        <ul key={`ul-${i}`} className="my-2 list-disc space-y-1 pl-5 text-sm">
          {items.map((item, li) => (
            <li key={li}>{renderInline(item, `li-${i}-${li}`, inline)}</li>
          ))}
        </ul>,
      );
      continue;
    }

    if (line.trim() === "") {
      i += 1;
      continue;
    }

    const buf: string[] = [line];
    i += 1;
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      !lines[i].match(/^(#{1,4}\s|[-*]\s|>\s|```)/)
    ) {
      buf.push(lines[i]);
      i += 1;
    }
    nodes.push(
      <p key={`p-${i}`} className="my-2 text-sm leading-relaxed">
        {renderInline(buf.join(" "), `p-${i}`, inline)}
      </p>,
    );
  }

  return <div className="max-w-none">{nodes}</div>;
}
