// pensieve production deployment via Pulumi.
//
// `pulumi package add terraform-module ../../terraform pensieveengine` generates
// the @pulumi/pensieveengine SDK wrapping the Terraform stack (single source of
// truth) — inputs/outputs keep the Terraform snake_case names.

import * as pulumi from "@pulumi/pulumi";
// Generated by `pulumi package add terraform-module ../../terraform pensieveengine`.
import * as pensieveengine from "@pulumi/pensieveengine";

const cfg = new pulumi.Config();

const engine = new pensieveengine.Module("pensieve", {
  project_name: cfg.get("projectName") ?? "pensieve",
  aws_region: cfg.get("awsRegion") ?? "us-east-1",
  supabase_org_id: cfg.require("supabaseOrgId"),
  supabase_db_password: cfg.requireSecret("supabaseDbPassword"),
  supabase_region: cfg.get("supabaseRegion") ?? "us-east-1",
  admin_emails: cfg.getObject<string[]>("adminEmails") ?? [],
  allowed_email_domains: cfg.getObject<string[]>("allowedEmailDomains") ?? [],
  oauth_providers: cfg.getObject<string[]>("oauthProviders") ?? [],
  domain: cfg.get("domain") ?? "",
  route53_zone_id: cfg.get("route53ZoneId") ?? "",
  image_tag: cfg.get("imageTag") ?? "latest",
});

export const engineUrl = engine.engine_url;
export const supabaseUrl = engine.supabase_url;
export const supabaseProjectRef = engine.supabase_project_ref;
export const bucketName = engine.bucket_name;
export const adminUser = engine.admin_user;
export const adminPassword = pulumi.secret(engine.admin_password);
export const logGroup = engine.log_group;
