[build]
builder = "DOCKERFILE"
dockerfilePath = "cloud/Dockerfile.api"
watchPatterns = ["cloud/api/**", "cloud/packages/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
