//! Brain repos — kyma's memory exposed as Git-clonable Obsidian vaults.
//!
//! A *brain* is a bare git repository served by `kyma serve` over smart HTTP
//! at `/git/<name>.git`. Its working tree is an Obsidian vault rendered
//! deterministically from the memory graph (scoped by a realm selector),
//! regenerated by a recurring export job, and accepting `git push` whose
//! markdown edits flow back into memory.
//!
//! This crate is the pure core: vault planning ([`vault`]), note rendering
//! ([`notes`]), MOC/index generation ([`moc`]), the git-binary wrapper
//! ([`gitbin`]), export orchestration ([`export`]), push-ingest planning
//! ([`ingest`]), pkt-line framing for the smart-HTTP advertisement
//! ([`pktline`]), and the registry types ([`registry`]). No axum, no sqlx —
//! `kyma-server` and `kyma-local` provide the HTTP surface, persistence, and
//! memory-table IO around it.

#![forbid(unsafe_code)]

pub mod registry;

#[cfg(test)]
mod registry_unit_tests;

pub mod types;

pub mod notes;

#[cfg(test)]
mod notes_unit_tests;

pub mod vault;

#[cfg(test)]
mod vault_unit_tests;

pub mod moc;

pub mod gardener;

pub mod gitbin;

#[cfg(test)]
mod gitbin_unit_tests;

pub mod export;

#[cfg(test)]
mod export_unit_tests;

pub mod ingest;

#[cfg(test)]
mod ingest_unit_tests;

pub mod pktline;

#[cfg(test)]
mod pktline_unit_tests;

/// Branch every brain repo serves and the exporter commits to.
pub const BRAIN_BRANCH: &str = "main";

/// Path of the exporter-owned manifest inside the vault tree.
pub const MANIFEST_PATH: &str = ".kyma/manifest.json";

/// `provenance.source` value on memory nodes ingested from a brain push.
pub const BRAIN_PROVENANCE_SOURCE: &str = "brain-repo";

/// Prefix of the deterministic upsert key for notes born from a push:
/// `brain:<brain-name>:<rel-path>`.
pub const TOPIC_KEY_PREFIX: &str = "brain:";

/// Prefix of the topic key that routes a memory into `wiki/`:
/// `wiki:<brain-name>:<page-slug>`.
pub const WIKI_TOPIC_PREFIX: &str = "wiki:";

/// Build the upsert key for a push-born note.
pub fn topic_key(brain: &str, rel_path: &str) -> String {
    format!("{TOPIC_KEY_PREFIX}{brain}:{rel_path}")
}

/// Errors surfaced by the brain core.
#[derive(Debug, thiserror::Error)]
pub enum BrainError {
    #[error("git binary unavailable")]
    GitUnavailable,
    #[error("git {op} failed: {detail}")]
    Git { op: &'static str, detail: String },
    #[error("invalid brain name: {0}")]
    InvalidName(String),
    #[error("invalid vault path: {0}")]
    InvalidPath(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("serde: {0}")]
    Serde(#[from] serde_json::Error),
    #[error("{0}")]
    Other(String),
}

/// Validate a brain name (also the repo directory stem): lowercase
/// alphanumeric plus `-`/`_`, 1–64 chars, must start alphanumeric.
pub fn validate_name(name: &str) -> Result<(), BrainError> {
    let ok = !name.is_empty()
        && name.len() <= 64
        && name.chars().next().is_some_and(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
        && name
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-' || c == '_');
    if ok {
        Ok(())
    } else {
        Err(BrainError::InvalidName(name.to_string()))
    }
}
