/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AppRouteImport } from './../routes/_app'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AppQueryRouteImport } from './../routes/_app.query'
import { Route as AppGraphRouteImport } from './../routes/_app.graph'
import { Route as AppExploreRouteImport } from './../routes/_app.explore'
import { Route as AppDiscoverRouteImport } from './../routes/_app.discover'
import { Route as AppDashboardsRouteImport } from './../routes/_app.dashboards'
import { Route as AppConnectorsRouteImport } from './../routes/_app.connectors'
import { Route as AppAgentRouteImport } from './../routes/_app.agent'
import { Route as AppConnectorsIndexRouteImport } from './../routes/_app.connectors.index'
import { Route as AppDashboardsIdRouteImport } from './../routes/_app.dashboards.$id'
import { Route as AppConnectorsIdRouteImport } from './../routes/_app.connectors.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsIndexRoute = AppConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectorsRoute,
} as any)
const AppDashboardsIdRoute = AppDashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardsRoute,
} as any)
const AppConnectorsIdRoute = AppConnectorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppConnectorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/agent': typeof AppAgentRoute
  '/connectors': typeof AppConnectorsRouteWithChildren
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/discover': typeof AppDiscoverRoute
  '/explore': typeof AppExploreRoute
  '/graph': typeof AppGraphRoute
  '/query': typeof AppQueryRoute
  '/connectors/$id': typeof AppConnectorsIdRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
  '/connectors/': typeof AppConnectorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/agent': typeof AppAgentRoute
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/discover': typeof AppDiscoverRoute
  '/explore': typeof AppExploreRoute
  '/graph': typeof AppGraphRoute
  '/query': typeof AppQueryRoute
  '/connectors/$id': typeof AppConnectorsIdRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
  '/connectors': typeof AppConnectorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/connectors': typeof AppConnectorsRouteWithChildren
  '/_app/dashboards': typeof AppDashboardsRouteWithChildren
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/query': typeof AppQueryRoute
  '/_app/connectors/$id': typeof AppConnectorsIdRoute
  '/_app/dashboards/$id': typeof AppDashboardsIdRoute
  '/_app/connectors/': typeof AppConnectorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/agent'
    | '/connectors'
    | '/dashboards'
    | '/discover'
    | '/explore'
    | '/graph'
    | '/query'
    | '/connectors/$id'
    | '/dashboards/$id'
    | '/connectors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/agent'
    | '/dashboards'
    | '/discover'
    | '/explore'
    | '/graph'
    | '/query'
    | '/connectors/$id'
    | '/dashboards/$id'
    | '/connectors'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/settings'
    | '/_app/agent'
    | '/_app/connectors'
    | '/_app/dashboards'
    | '/_app/discover'
    | '/_app/explore'
    | '/_app/graph'
    | '/_app/query'
    | '/_app/connectors/$id'
    | '/_app/dashboards/$id'
    | '/_app/connectors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/': {
      id: '/_app/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AppConnectorsIndexRouteImport
      parentRoute: typeof AppConnectorsRoute
    }
    '/_app/dashboards/$id': {
      id: '/_app/dashboards/$id'
      path: '/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof AppDashboardsIdRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/connectors/$id': {
      id: '/_app/connectors/$id'
      path: '/$id'
      fullPath: '/connectors/$id'
      preLoaderRoute: typeof AppConnectorsIdRouteImport
      parentRoute: typeof AppConnectorsRoute
    }
  }
}

interface AppConnectorsRouteChildren {
  AppConnectorsIdRoute: typeof AppConnectorsIdRoute
  AppConnectorsIndexRoute: typeof AppConnectorsIndexRoute
}

const AppConnectorsRouteChildren: AppConnectorsRouteChildren = {
  AppConnectorsIdRoute: AppConnectorsIdRoute,
  AppConnectorsIndexRoute: AppConnectorsIndexRoute,
}

const AppConnectorsRouteWithChildren = AppConnectorsRoute._addFileChildren(
  AppConnectorsRouteChildren,
)

interface AppDashboardsRouteChildren {
  AppDashboardsIdRoute: typeof AppDashboardsIdRoute
}

const AppDashboardsRouteChildren: AppDashboardsRouteChildren = {
  AppDashboardsIdRoute: AppDashboardsIdRoute,
}

const AppDashboardsRouteWithChildren = AppDashboardsRoute._addFileChildren(
  AppDashboardsRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppConnectorsRoute: typeof AppConnectorsRouteWithChildren
  AppDashboardsRoute: typeof AppDashboardsRouteWithChildren
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppExploreRoute: typeof AppExploreRoute
  AppGraphRoute: typeof AppGraphRoute
  AppQueryRoute: typeof AppQueryRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppConnectorsRoute: AppConnectorsRouteWithChildren,
  AppDashboardsRoute: AppDashboardsRouteWithChildren,
  AppDiscoverRoute: AppDiscoverRoute,
  AppExploreRoute: AppExploreRoute,
  AppGraphRoute: AppGraphRoute,
  AppQueryRoute: AppQueryRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
