/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as AppRouteImport } from './../routes/_app'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AppExploreRouteImport } from './../routes/_app.explore'
import { Route as AppDashboardsRouteImport } from './../routes/_app.dashboards'
import { Route as AppDashboardsIdRouteImport } from './../routes/_app.dashboards.$id'
import { Route as AppAgentRouteImport } from './../routes/_app.agent'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsIdRoute = AppDashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardsRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/agent': typeof AppAgentRoute
  '/explore': typeof AppExploreRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/agent': typeof AppAgentRoute
  '/explore': typeof AppExploreRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/settings': typeof SettingsRoute
  '/_app/dashboards': typeof AppDashboardsRouteWithChildren
  '/_app/agent': typeof AppAgentRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/dashboards/$id': typeof AppDashboardsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/dashboards' | '/agent' | '/explore' | '/dashboards/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/dashboards' | '/agent' | '/explore' | '/dashboards/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/settings'
    | '/_app/dashboards'
    | '/_app/agent'
    | '/_app/explore'
    | '/_app/dashboards/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/$id': {
      id: '/_app/dashboards/$id'
      path: '/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof AppDashboardsIdRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppDashboardsRouteChildren {
  AppDashboardsIdRoute: typeof AppDashboardsIdRoute
}

const AppDashboardsRouteChildren: AppDashboardsRouteChildren = {
  AppDashboardsIdRoute: AppDashboardsIdRoute,
}

const AppDashboardsRouteWithChildren = AppDashboardsRoute._addFileChildren(
  AppDashboardsRouteChildren,
)

interface AppRouteChildren {
  AppDashboardsRoute: typeof AppDashboardsRouteWithChildren
  AppAgentRoute: typeof AppAgentRoute
  AppExploreRoute: typeof AppExploreRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardsRoute: AppDashboardsRouteWithChildren,
  AppAgentRoute: AppAgentRoute,
  AppExploreRoute: AppExploreRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
