/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SetupRouteImport } from './../routes/setup'
import { Route as SettingsRouteImport } from './../routes/settings'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as AppRouteImport } from './../routes/_app'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AppQueryRouteImport } from './../routes/_app.query'
import { Route as AppMemoryRouteImport } from './../routes/_app.memory'
import { Route as AppTracesRouteImport } from './../routes/_app.traces'
import { Route as AppGraphRouteImport } from './../routes/_app.graph'
import { Route as AppExploreRouteImport } from './../routes/_app.explore'
import { Route as AppDiscoverRouteImport } from './../routes/_app.discover'
import { Route as AppDashboardsRouteImport } from './../routes/_app.dashboards'
import { Route as AppCredentialsRouteImport } from './../routes/_app.credentials'
import { Route as AppConnectorsRouteImport } from './../routes/_app.connectors'
import { Route as AppAgentRouteImport } from './../routes/_app.agent'
import { Route as AppMemoryIndexRouteImport } from './../routes/_app.memory.index'
import { Route as AppDashboardsIndexRouteImport } from './../routes/_app.dashboards.index'
import { Route as AppConnectorsIndexRouteImport } from './../routes/_app.connectors.index'
import { Route as AppMemorySettingsRouteImport } from './../routes/_app.memory.settings'
import { Route as AppMemorySearchRouteImport } from './../routes/_app.memory.search'
import { Route as AppMemoryReviewRouteImport } from './../routes/_app.memory.review'
import { Route as AppMemoryOverviewRouteImport } from './../routes/_app.memory.overview'
import { Route as AppMemoryDreamingRouteImport } from './../routes/_app.memory.dreaming'
import { Route as AppDashboardsIdRouteImport } from './../routes/_app.dashboards.$id'
import { Route as AppConnectorsIdRouteImport } from './../routes/_app.connectors.$id'
import { Route as AppMemoryReviewIndexRouteImport } from './../routes/_app.memory.review.index'
import { Route as AppMemoryDreamingIndexRouteImport } from './../routes/_app.memory.dreaming.index'
import { Route as AppMemoryDreamingRunIdRouteImport } from './../routes/_app.memory.dreaming.$runId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesRoute = AppTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsRoute = AppConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryIndexRoute = AppMemoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppDashboardsIndexRoute = AppDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardsRoute,
} as any)
const AppConnectorsIndexRoute = AppConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectorsRoute,
} as any)
const AppMemorySettingsRoute = AppMemorySettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemorySearchRoute = AppMemorySearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemoryReviewRoute = AppMemoryReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemoryOverviewRoute = AppMemoryOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppMemoryDreamingRoute = AppMemoryDreamingRouteImport.update({
  id: '/dreaming',
  path: '/dreaming',
  getParentRoute: () => AppMemoryRoute,
} as any)
const AppDashboardsIdRoute = AppDashboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDashboardsRoute,
} as any)
const AppConnectorsIdRoute = AppConnectorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppConnectorsRoute,
} as any)
const AppMemoryReviewIndexRoute = AppMemoryReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMemoryReviewRoute,
} as any)
const AppMemoryDreamingIndexRoute = AppMemoryDreamingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMemoryDreamingRoute,
} as any)
const AppMemoryDreamingRunIdRoute = AppMemoryDreamingRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AppMemoryDreamingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/agent': typeof AppAgentRoute
  '/connectors': typeof AppConnectorsRouteWithChildren
  '/credentials': typeof AppCredentialsRoute
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/discover': typeof AppDiscoverRoute
  '/explore': typeof AppExploreRoute
  '/graph': typeof AppGraphRoute
  '/memory': typeof AppMemoryRouteWithChildren
  '/query': typeof AppQueryRoute
  '/traces': typeof AppTracesRoute
  '/connectors/$id': typeof AppConnectorsIdRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
  '/memory/dreaming': typeof AppMemoryDreamingRouteWithChildren
  '/memory/overview': typeof AppMemoryOverviewRoute
  '/memory/review': typeof AppMemoryReviewRouteWithChildren
  '/memory/search': typeof AppMemorySearchRoute
  '/memory/settings': typeof AppMemorySettingsRoute
  '/connectors/': typeof AppConnectorsIndexRoute
  '/dashboards/': typeof AppDashboardsIndexRoute
  '/memory/': typeof AppMemoryIndexRoute
  '/memory/dreaming/$runId': typeof AppMemoryDreamingRunIdRoute
  '/memory/dreaming/': typeof AppMemoryDreamingIndexRoute
  '/memory/review/': typeof AppMemoryReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/agent': typeof AppAgentRoute
  '/credentials': typeof AppCredentialsRoute
  '/discover': typeof AppDiscoverRoute
  '/explore': typeof AppExploreRoute
  '/graph': typeof AppGraphRoute
  '/query': typeof AppQueryRoute
  '/traces': typeof AppTracesRoute
  '/connectors/$id': typeof AppConnectorsIdRoute
  '/dashboards/$id': typeof AppDashboardsIdRoute
  '/memory/overview': typeof AppMemoryOverviewRoute
  '/memory/search': typeof AppMemorySearchRoute
  '/memory/settings': typeof AppMemorySettingsRoute
  '/connectors': typeof AppConnectorsIndexRoute
  '/dashboards': typeof AppDashboardsIndexRoute
  '/memory': typeof AppMemoryIndexRoute
  '/memory/dreaming/$runId': typeof AppMemoryDreamingRunIdRoute
  '/memory/dreaming': typeof AppMemoryDreamingIndexRoute
  '/memory/review': typeof AppMemoryReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/connectors': typeof AppConnectorsRouteWithChildren
  '/_app/credentials': typeof AppCredentialsRoute
  '/_app/dashboards': typeof AppDashboardsRouteWithChildren
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/memory': typeof AppMemoryRouteWithChildren
  '/_app/query': typeof AppQueryRoute
  '/_app/traces': typeof AppTracesRoute
  '/_app/connectors/$id': typeof AppConnectorsIdRoute
  '/_app/dashboards/$id': typeof AppDashboardsIdRoute
  '/_app/memory/dreaming': typeof AppMemoryDreamingRouteWithChildren
  '/_app/memory/overview': typeof AppMemoryOverviewRoute
  '/_app/memory/review': typeof AppMemoryReviewRouteWithChildren
  '/_app/memory/search': typeof AppMemorySearchRoute
  '/_app/memory/settings': typeof AppMemorySettingsRoute
  '/_app/connectors/': typeof AppConnectorsIndexRoute
  '/_app/dashboards/': typeof AppDashboardsIndexRoute
  '/_app/memory/': typeof AppMemoryIndexRoute
  '/_app/memory/dreaming/$runId': typeof AppMemoryDreamingRunIdRoute
  '/_app/memory/dreaming/': typeof AppMemoryDreamingIndexRoute
  '/_app/memory/review/': typeof AppMemoryReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/agent'
    | '/connectors'
    | '/credentials'
    | '/dashboards'
    | '/discover'
    | '/explore'
    | '/graph'
    | '/memory'
    | '/query'
    | '/traces'
    | '/connectors/$id'
    | '/dashboards/$id'
    | '/memory/dreaming'
    | '/memory/overview'
    | '/memory/review'
    | '/memory/search'
    | '/memory/settings'
    | '/connectors/'
    | '/dashboards/'
    | '/memory/'
    | '/memory/dreaming/$runId'
    | '/memory/dreaming/'
    | '/memory/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/agent'
    | '/credentials'
    | '/discover'
    | '/explore'
    | '/graph'
    | '/query'
    | '/traces'
    | '/connectors/$id'
    | '/dashboards/$id'
    | '/memory/overview'
    | '/memory/search'
    | '/memory/settings'
    | '/connectors'
    | '/dashboards'
    | '/memory'
    | '/memory/dreaming/$runId'
    | '/memory/dreaming'
    | '/memory/review'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/settings'
    | '/setup'
    | '/_app/agent'
    | '/_app/connectors'
    | '/_app/credentials'
    | '/_app/dashboards'
    | '/_app/discover'
    | '/_app/explore'
    | '/_app/graph'
    | '/_app/memory'
    | '/_app/query'
    | '/_app/traces'
    | '/_app/connectors/$id'
    | '/_app/dashboards/$id'
    | '/_app/memory/dreaming'
    | '/_app/memory/overview'
    | '/_app/memory/review'
    | '/_app/memory/search'
    | '/_app/memory/settings'
    | '/_app/connectors/'
    | '/_app/dashboards/'
    | '/_app/memory/'
    | '/_app/memory/dreaming/$runId'
    | '/_app/memory/dreaming/'
    | '/_app/memory/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces': {
      id: '/_app/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AppTracesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials': {
      id: '/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors': {
      id: '/_app/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AppConnectorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory/': {
      id: '/_app/memory/'
      path: '/'
      fullPath: '/memory/'
      preLoaderRoute: typeof AppMemoryIndexRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/connectors/': {
      id: '/_app/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AppConnectorsIndexRouteImport
      parentRoute: typeof AppConnectorsRoute
    }
    '/_app/memory/settings': {
      id: '/_app/memory/settings'
      path: '/settings'
      fullPath: '/memory/settings'
      preLoaderRoute: typeof AppMemorySettingsRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/search': {
      id: '/_app/memory/search'
      path: '/search'
      fullPath: '/memory/search'
      preLoaderRoute: typeof AppMemorySearchRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/review': {
      id: '/_app/memory/review'
      path: '/review'
      fullPath: '/memory/review'
      preLoaderRoute: typeof AppMemoryReviewRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/overview': {
      id: '/_app/memory/overview'
      path: '/overview'
      fullPath: '/memory/overview'
      preLoaderRoute: typeof AppMemoryOverviewRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/memory/dreaming': {
      id: '/_app/memory/dreaming'
      path: '/dreaming'
      fullPath: '/memory/dreaming'
      preLoaderRoute: typeof AppMemoryDreamingRouteImport
      parentRoute: typeof AppMemoryRoute
    }
    '/_app/dashboards/$id': {
      id: '/_app/dashboards/$id'
      path: '/$id'
      fullPath: '/dashboards/$id'
      preLoaderRoute: typeof AppDashboardsIdRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/connectors/$id': {
      id: '/_app/connectors/$id'
      path: '/$id'
      fullPath: '/connectors/$id'
      preLoaderRoute: typeof AppConnectorsIdRouteImport
      parentRoute: typeof AppConnectorsRoute
    }
    '/_app/memory/review/': {
      id: '/_app/memory/review/'
      path: '/'
      fullPath: '/memory/review/'
      preLoaderRoute: typeof AppMemoryReviewIndexRouteImport
      parentRoute: typeof AppMemoryReviewRoute
    }
    '/_app/memory/dreaming/': {
      id: '/_app/memory/dreaming/'
      path: '/'
      fullPath: '/memory/dreaming/'
      preLoaderRoute: typeof AppMemoryDreamingIndexRouteImport
      parentRoute: typeof AppMemoryDreamingRoute
    }
    '/_app/memory/dreaming/$runId': {
      id: '/_app/memory/dreaming/$runId'
      path: '/$runId'
      fullPath: '/memory/dreaming/$runId'
      preLoaderRoute: typeof AppMemoryDreamingRunIdRouteImport
      parentRoute: typeof AppMemoryDreamingRoute
    }
  }
}

interface AppConnectorsRouteChildren {
  AppConnectorsIdRoute: typeof AppConnectorsIdRoute
  AppConnectorsIndexRoute: typeof AppConnectorsIndexRoute
}

const AppConnectorsRouteChildren: AppConnectorsRouteChildren = {
  AppConnectorsIdRoute: AppConnectorsIdRoute,
  AppConnectorsIndexRoute: AppConnectorsIndexRoute,
}

const AppConnectorsRouteWithChildren = AppConnectorsRoute._addFileChildren(
  AppConnectorsRouteChildren,
)

interface AppDashboardsRouteChildren {
  AppDashboardsIdRoute: typeof AppDashboardsIdRoute
  AppDashboardsIndexRoute: typeof AppDashboardsIndexRoute
}

const AppDashboardsRouteChildren: AppDashboardsRouteChildren = {
  AppDashboardsIdRoute: AppDashboardsIdRoute,
  AppDashboardsIndexRoute: AppDashboardsIndexRoute,
}

const AppDashboardsRouteWithChildren = AppDashboardsRoute._addFileChildren(
  AppDashboardsRouteChildren,
)

interface AppMemoryDreamingRouteChildren {
  AppMemoryDreamingRunIdRoute: typeof AppMemoryDreamingRunIdRoute
  AppMemoryDreamingIndexRoute: typeof AppMemoryDreamingIndexRoute
}

const AppMemoryDreamingRouteChildren: AppMemoryDreamingRouteChildren = {
  AppMemoryDreamingRunIdRoute: AppMemoryDreamingRunIdRoute,
  AppMemoryDreamingIndexRoute: AppMemoryDreamingIndexRoute,
}

const AppMemoryDreamingRouteWithChildren =
  AppMemoryDreamingRoute._addFileChildren(AppMemoryDreamingRouteChildren)

interface AppMemoryReviewRouteChildren {
  AppMemoryReviewIndexRoute: typeof AppMemoryReviewIndexRoute
}

const AppMemoryReviewRouteChildren: AppMemoryReviewRouteChildren = {
  AppMemoryReviewIndexRoute: AppMemoryReviewIndexRoute,
}

const AppMemoryReviewRouteWithChildren = AppMemoryReviewRoute._addFileChildren(
  AppMemoryReviewRouteChildren,
)

interface AppMemoryRouteChildren {
  AppMemoryDreamingRoute: typeof AppMemoryDreamingRouteWithChildren
  AppMemoryOverviewRoute: typeof AppMemoryOverviewRoute
  AppMemoryReviewRoute: typeof AppMemoryReviewRouteWithChildren
  AppMemorySearchRoute: typeof AppMemorySearchRoute
  AppMemorySettingsRoute: typeof AppMemorySettingsRoute
  AppMemoryIndexRoute: typeof AppMemoryIndexRoute
}

const AppMemoryRouteChildren: AppMemoryRouteChildren = {
  AppMemoryDreamingRoute: AppMemoryDreamingRouteWithChildren,
  AppMemoryOverviewRoute: AppMemoryOverviewRoute,
  AppMemoryReviewRoute: AppMemoryReviewRouteWithChildren,
  AppMemorySearchRoute: AppMemorySearchRoute,
  AppMemorySettingsRoute: AppMemorySettingsRoute,
  AppMemoryIndexRoute: AppMemoryIndexRoute,
}

const AppMemoryRouteWithChildren = AppMemoryRoute._addFileChildren(
  AppMemoryRouteChildren,
)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppConnectorsRoute: typeof AppConnectorsRouteWithChildren
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppDashboardsRoute: typeof AppDashboardsRouteWithChildren
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppExploreRoute: typeof AppExploreRoute
  AppGraphRoute: typeof AppGraphRoute
  AppMemoryRoute: typeof AppMemoryRouteWithChildren
  AppQueryRoute: typeof AppQueryRoute
  AppTracesRoute: typeof AppTracesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppConnectorsRoute: AppConnectorsRouteWithChildren,
  AppCredentialsRoute: AppCredentialsRoute,
  AppDashboardsRoute: AppDashboardsRouteWithChildren,
  AppDiscoverRoute: AppDiscoverRoute,
  AppExploreRoute: AppExploreRoute,
  AppGraphRoute: AppGraphRoute,
  AppMemoryRoute: AppMemoryRouteWithChildren,
  AppQueryRoute: AppQueryRoute,
  AppTracesRoute: AppTracesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
